### ISSUE TITLE
提几个问题，希望看一看

### ISSUE THREAD

**Issue by TZZhan** [KittenYang/KYElegantPhotoGallery#2]
首先小图放成大图之前那个将近是马赛克的小图不太好看，还有就是总觉得有些卡顿，不是很流畅，最大的问题就是，你这六张图就占用了150MB的内存，这太夸张了，程序很容易就被干掉了

**Comment by KittenYang** [comment]
@TZZhan  1.因为有gif图，这是SDWebImage的通病  2.用了GPU模糊算法  如果换成普通图片并且模糊用的是iOS8中的UIBlurEffect就完全没有问题了。

**Comment by TZZhan** [comment]
多谢解答，希望越做越好

**Comment by KittenYang** [comment]
@TZZhan  fixed!
