### ISSUE TITLE
崩溃问题

### ISSUE THREAD

**Issue by HarveyDawn** [KittenYang/KYElegantPhotoGallery#5]
点击一幅小图加载大图的时候，当没有100%加载完成时，立马点击另一幅图会引起奔溃

**Comment by KittenYang** [comment]
@HarveyZone  感谢提出，稍后修复。

**Comment by lukewcn** [comment]
这个问题很容易复现

**Comment by doa-ilyasyurdaon** [comment]
Do not ever use this gallery!!! It has a highly reproducible bug and the "developer" moron apparently wants to fix it 34423525 years later.
